version: "3"

services:
  app-server:
    build:
      context: .
      args: 
        app_port: 8085
      #   app_db: app-db:30000
      #   app_env: alpha
    command: npm run debug
    container_name: app-server
    restart: always
    volumes:
      - ./dist:/app/server/dist
    ports:
      - "8085:8085"
      - "5858:5858"
    links:
      - app-db
    environment:
     - NODEJS_PORT=8085
     - NODE_ENV=alpha
     - MONGO_HOST=app-db:27017
     - NODEJS_IP=0.0.0.0
      
  app-db:
    container_name: app-db
    image: mongo:3.6.5
    ports:
      - "30000:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
      driver: local